---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: influxdb_centos7
    privileged: true
    image: centos:7
    docker_host: "${DOCKER_HOST}"
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  config_options:
    defaults:
      pipelining: true
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: tmp/ansible-facts
      fact_caching_timeout: 300
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    v: true
    s: true
  lint:
    name: flake8
