#!/bin/bash -xe

BIN_DIR="${0%/*}"
PRJ_ROOT_DIR=
VENV_NAME="jenkins-venv"

export PYENV_ROOT="${HOME}/.pyenv"
export PATH="${PYENV_ROOT}/bin:${PATH}"

[ -d "${PYENV_ROOT}" ] || git clone https://github.com/pyenv/pyenv.git ${PYENV_ROOT}

eval "$(pyenv init -)"

cd ${BIN_DIR}/../
PRJ_ROOT_DIR="${PWD}"
echo "INFO: running in directory $PRJ_ROOT_DIR"

PYENV_VERSION=2.7.15 pyenv version || pyenv install 2.7.15

pyenv local 2.7.15
pyenv versions

virtualenv -p python .venv
. .venv/bin/activate
pip install -r test-requirements.txt

pyenv rehash
